### PR TITLE
resolves #146 reload the browser when using watch mode with preview

### LINKED ISSUE #146: watch and preview are incompatible
I thought that using both `-w` and `--preview` would be effectively provide a "LiveReload" within the Chromium window.

In fact the options are exclusive so when used together the watch no longer occurs and there is no change to the browser window when the source file changes.

I'm not sure if it's possible to have this, I think that's probably what users might expect or at least what I would like. I would like to write my document in one window/monitor and see the changes occur to the html in the other window/monitor.

I guess this could also be done in other ways..

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #146

### CODE REVIEW

**Comment by Mogztter** [comment]
@danyill I would love your feedback on this feature/bugfix

**Comment by danyill** [comment]
Very happy to. I'm not very familiar with installing packages from source. I think all I need to do is:

```bash
npm i
npm link
```

I received some errors when running `npm link`:

```bash
> ghostscript4js@3.1.1 install /home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/ghostscript4js
> node-gyp rebuild

make: Entering directory '/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/ghostscript4js/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/ghostscript4js/src/ghostscript4js.o
  SOLINK_MODULE(target) Release/obj.target/ghostscript4js.node
g++: error: /usr/lib/x86_64-linux-gnu/libgs.so: No such file or directory
make: *** [ghostscript4js.target.mk:131: Release/obj.target/ghostscript4js.node] Error 1
make: Leaving directory '/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/ghostscript4js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mulhollandd/.nvm/versions/node/v11.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 5.3.0-24-generic
gyp ERR! command "/home/mulhollandd/.nvm/versions/node/v11.3.0/bin/node" "/home/mulhollandd/.nvm/versions/node/v11.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/ghostscript4js
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
```

I think this means there is a dependency required (maybe just for development?). On Ubuntu to resolve I need `sudo apt install libgs-dev`. According to `package-lock.json` this is optional and I am not entirely familiar with the way the npm packaging works.

However the feature works great :tada: :tada: :tada: Big thank you :heart_eyes: 

I'd say it's a game changer for end-users:

1. Because it's just reloading the page setting a zoom level in the headless Chrome/Chromium works fine (doesn't have to be adjusted after each change).
2. It's fast -- visual feedback is really helpful when working with paged media. It's not so fast that I can't occasionally make a change, press save and not see it pick up the change but I don't think this is a big deal.
3. It's also neat that it picks up on stylesheet/template changes.

**Comment by Mogztter** [comment]
I think we need to go one step further and introduce a proper browser instance where we can execute tasks sequentially or in parallel.
For instance, when we convert a multiple files at once we don't want to execute tasks sequentially:

```console
asciidoctor-pdf a.doc b.adoc c.adoc d.adoc e.adoc f.adoc ...
```

In this case, I think that the right approach is to open each file in a dedicated page/tab.
We also need to debounce and execute events sequentially when watch mode is enabled because Chrome cannot print a page if there's already an active printing job:

```
Error: Protocol error (Page.printToPDF): The previous printing job hasn't finished
    at Promise (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor-pdf.js/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor-pdf.js/node_modules/puppeteer/lib/Connection.js:182:12)
    at Page.pdf (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor-pdf.js/node_modules/puppeteer/lib/Page.js:1007:39)
    at Page.<anonymous> (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor-pdf.js/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.convert (/home/guillaume/workspace/opensource/asciidoctor/asciidoctor-pdf.js/lib/converter.js:93:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by danyill** [comment]
I've just been looking at the html output but I am seeing some errors in the console as I keep making changes to the document or stylesheet:

```
(node:11468) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pageerror listeners added. Use emitter.setMaxListeners() to increase limit
(node:11468) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
```

I don't know if this matters.

And also:

```
error TypeError: node.getHeader(...).getTitle is not a function
    at document (/home/mulhollandd/Documents/asciidoctor-cheat-sheet/base/template.js:52:26)
    at TemplateConverter.convert (/home/mulhollandd/Documents/asciidoctor-pdf.js/lib/converter.js:23:16)
    at constructor.$$convert (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:7948:35)
    at Function.$$convert (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:15815:22)
    at $$3 (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:15882:21)
    at Object.Opal.yield1 (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/opal.js:1452:14)
    at /home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/nodejs.js:319:21
    at Function.$$open (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/nodejs.js:322:14)
    at Opal.send (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
    at Function.$$convert_file (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:15875:14)
```

**Comment by Mogztter** [comment]
Thanks for your feedback @danyill 
It's better than what we have now but I want to make sure that I don't break existing use cases. I will play a bit more with this feature before merging.

In the meantime, if you have suggestions, feel free to add a comment :wink:

**Comment by danyill** [comment]
Well, here's another suggestion.

Most PDF viewers (especially on Windows) don't autorefresh if a PDF file changes. I've been using the following to generate updated `html` and `pdf` files which is perhaps a bit klunky if we can make the user's life easier:

```bash
#!/bin/bash
while sleep 1 ;
  do find . -name '*.adoc' -or -name '*.js' -or -name '*.css'| entr -d asciidoctor-pdf --template-require ./base/template.js -S unsafe test.adoc; 
```

It would be nice if watch mode and preview mode also generated the pdf (I think as you suggest above) and also produced a preview perhaps using `pdf.js` for example. This might only require opening a tab and re-using the logic you've already created. My hacky attempt ([copied off this from stackoverflow](https://stackoverflow.com/questions/7401292/how-to-refresh-automatically-on-a-pdf-viewer?answertab=active#tab-top) is something like this:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta http-equiv="content-type" content="text/html; charset=windows-1252">
    <title>PDF Preview</title>

    <script type="text/javascript">
       var timer = null;

       function refresh(){
          var d = document.getElementById("pdf"); // gets pdf-div
          d.innerHTML = '<embed src="test.pdf" width="' + screen.availWidth + '" height="' + screen.availHeight + '">';
       }

       function autoRefresh(){
          timer = setTimeout("autoRefresh()", 5000);
          refresh();
       }

       function manualRefresh(){
          clearTimeout(timer); 
          refresh();   
       }

    </script>

</head>
<body>
   <button onclick="manualRefresh()">manual refresh</button>
   <button onclick="autoRefresh()">auto refresh</button>
   <div id="pdf"></div>
</body> 
<script type="text/javascript">refresh();</script>
</html>
```

Which has the annoying glitch problem for auto-refresh because it is not "hooked in" to watch mode.
So one option for producing a pdf is to create an html file and open it which embeds `pdf.js` and then automatically refresh it by controlling the headless chrome.

The other solution I've found in the world of OSS software is that the TeXworks PDF viewer (not perhaps very accessible) and the Evince viewer (not cross platform I think) will automatically refresh a pdf (the TeXworks PDF viewer does this very smoothly).

Thoughts?

**Comment by Mogztter** [comment]
> I received some errors when running npm link

Yes `ghostscript` is a development dependency that requires system libraries.

> I've just been looking at the html output but I am seeing some errors in the console as I keep making changes to the document or stylesheet:

I can reproduce this issue, I will take a look :eyes: 

>error TypeError: node.getHeader(...).getTitle is not a function

I don't think this error is related.
I think you should check that `node.getHeader()` returns something in your template (`/home/mulhollandd/Documents/asciidoctor-cheat-sheet/base/template.js`).

> So one option for producing a pdf is to create an html file and open it which embeds pdf.js and then automatically refresh it by controlling the headless chrome.
The other solution I've found in the world of OSS software is that the TeXworks PDF viewer (not perhaps very accessible) and the Evince viewer (not cross platform I think) will automatically refresh a pdf (the TeXworks PDF viewer does this very smoothly).

Chrome can be used as a PDF viewer.
Puppeteer can open a new page and go to `file:///path/to/file.pdf`.
The problem is that we produce two files, one HTML file and one PDF file.
So we need to decide what we should do when the `--preview` option is present. A few options:

- Open both files in two pages/tabs
- `--preview` takes an optional value, `html` or `pdf` (by default `html`) to open the HTML file or the PDF file in the browser
- ... ?

I will create an issue for each task.

**Comment by Mogztter** [comment]
@danyill I've made some changes to fix the "EventEmitter memory leak detected" and "The previous printing job hasn't finished" bugs.

I've also opened an issue to preview the generated PDF: https://github.com/Mogztter/asciidoctor-pdf.js/issues/150

**Comment by danyill** [comment]
Unless I've messed up the installation, the "watch" part is no longer working with the latest changes -- I'm not getting any auto-refresh and the console is not showing any changes as I change the files (`css` or `adoc`).

**Comment by Mogztter** [comment]
> and the console is not showing any changes as I change the files (css or adoc).

Could you try to enable the verbose mode with `--verbose`?

> Unless I've messed up the installation, the "watch" part is no longer working with the latest changes

Could you please share the exact command you are running? I will try to reproduce on my machine.

**Comment by danyill** [comment]
Sure. I'm using `asciidoctor-pdf --verbose --watch --preview --template-require ./base/template.js -S unsafe asciidoctor-cheat-sheet.adoc`

**Comment by Mogztter** [comment]
I cannot reproduce this issue:

live-reload


I'm using the following command (directly from the workspace):

```console
$ ./bin/asciidoctor-pdf examples/document/basic-example.adoc --watch --preview -verbose
require undefined
backend html5
doctype undefined
standalone true
section-numbers false
failure-level FATAL
quiet false
verbose true
timings false
trace false
base-dir undefined
destination-dir undefined
verbose-mode 2
attributes 
options {"backend":"html5","safe":"unsafe","standalone":true,"failure_level":4,"verbose":2,"timings":false,"trace":false,"mkdirs":true,"attributes":[]}
converting file examples/document/basic-example.adoc
Watch mode entered, needs to be manually terminated using Ctrl+C!
  file changed examples/document/basic-example.adoc
converting file examples/document/basic-example.adoc
  file changed examples/document/basic-example.adoc
converting file examples/document/basic-example.adoc
  file changed examples/document/basic-example.adoc
converting file examples/document/basic-example.adoc
```

**Comment by danyill** [comment]
@Mogztter sorry, the problem was me :frowning:. I had done something silly with my branching in git and so I was not on the correct commit. I'll do some more testing later today, thanks for looking into it.

**Comment by danyill** [comment]
@Mogztter possibly this should be a separate issue but because they're coupled and this PR is still open I'll comment here, hope that's OK.

I've been using watch mode (but without preview) for the last few days and using `evince` to auto-reload the pdf after rendering because I like to be able to see both the html and the pdf at the same time (I just manually refresh my browser window and evince auto-refreshes).

I use a command like:

    asciidoctor-pdf --trace --verbose --watch --template-require ./base/template.js -S unsafe asciidoctor-cheat-sheet.adoc

Frequently (at least 1 save in 10 but sometimes 1 in 3 or 4) when using watch mode I end up with a pdf which isn't properly rendered. It produces the header but no content, like this:

image

When it should produce something more like:

image

There doesn't seem to be an error message.

When I use the following script, this never happens:

```bash
#!/bin/bash
while sleep 1 ;
  do find . -name '*.adoc' -or -name '*.js' -or -name '*.css'| entr -d asciidoctor-pdf --template-require ./base/template.js -S unsafe asciidoctor-cheat-sheet.adoc; 
done
```

I'm not sure how to diagnose further, here is my [repo](https://gitlab.com/danyill/asciidoctor-quick-reference/) (a work in progress). It could be that `asciidoctor-pdf` is reading the file before the save within the code editor completes? I have a suspicion that the larger the asciidoc file gets the more frequently this happens (but have not checked in detail).

**Comment by Mogztter** [comment]
> I'm not sure how to diagnose further, here is my repo (a work in progress).

I think the repository is private (ie. I get a 404 not found). My username on GitLab.com is `@g.grossetie`.

> It could be that asciidoctor-pdf is reading the file before the save within the code editor completes? I have a suspicion that the larger the asciidoc file gets the more frequently this happens (but have not checked in detail).

Not sure...
Looking at the screenshot, it looks like the Asciidoctor Document object is empty (the title is undefined, it has no section...). What is "Footnotes" ? A section title ? A static title ?
Do you use external resources like Google fonts? Could you try to use only local resources?

**Comment by Mogztter** [comment]
> possibly this should be a separate issue but because they're coupled and this PR is still open I'll comment here, hope that's OK

Please open a new issue while we are trying to pin point the root cause.

**Pull request merged**
