### PR TITLE
Remove the table outer border to improve the rendering

### PR DESCRIPTION
**Pull request by Mogztter**
I've removed the outer border on the table (defined in the default Asciidoctor stylesheet):

**before**
before

**after**
after

ping @oncletom 😄 

//cc @mojavelinux Maybe we should update the default stylesheet ? I didn't notice any visual difference in the browser (Chrome and Firefox)

### CODE REVIEW

**Comment by mojavelinux** [comment]
I could be wrong, but I think it's used once you start getting into various combinations of frame and grid. The border is configured to collapse, so it should just fuse with the borders from the cells.

**Comment by Mogztter** [comment]
Yes but I think we should use cell borders (configured to collapse) instead of an outer border defined on the table. The rendering looks the same but the main advantage is that if the table is spread on multiple pages then the border will not be visible when the row ends at the end of a page (see the bottom of the page) and the repeated table header will have a top border (see the top of the page).
Does it make sense ?

**Comment by mojavelinux** [comment]
I see what you're saying. Yes, that makes perfect sense. Let's address this in the default stylesheet.

**Comment by Mogztter** [comment]
I've created an issue upstream.
In the meantime I'm merging this fix.

**Comment by mojavelinux** [comment]
> Yes but I think we should use cell borders (configured to collapse) instead of an outer border defined on the table.

The problem with this approach is that it's not possible to achieve all the permutations of frame and grid that are supported today (in the way they are supported). We'd have to abandon the current behavior and define a new behavior based on cell collapsing. So there are tradeoffs. You fix some things, but then you break others.

**Pull request merged**
