### PR TITLE
resolves #73 upgrade to MathJax 3.0.0

### LINKED ISSUE #73: Upgrade to MathJax 3.0.0
For reference: https://github.com/asciidoctor/asciidoctor-browser-extension/commit/0e05367d026cdf7b219844f8b2d076c714ce6807

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #73

//cc @ahus1

### CODE REVIEW

**Comment by ahus1** [comment]
I assume you cc'ed me as I added the initial MathJax PR. My first iteration used the MathJax version used in Asciidoctor HTML5. I wanted to have a 1:1 compatibility. As the rendered documents look fine, I think its ok to upgrade, although the test suite is not extensive.

As you touched the eqnumsValue in this change: I think the logic is now different from the html5.rb logic; here he excerpt: 

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L265-L266

```ruby
      eqnums_val = node.attr 'eqnums', 'none'
      eqnums_val = 'AMS' if eqnums_val.empty?
```

If I understand this correctly, it evaluates to:
* eqnums not defined -> 'none'
* eqnums empty string -> 'AMS'
* eqnums any other value -> any other value

The original code in `stem.js` mapped an empty string to `AMS`, the new code doesn't. 
I suggest you add a case for mapping an empty string to `AMS`.

After that change I don't have other comments and it's ready to be merged.

**Comment by Mogztter** [comment]
> I assume you cc'ed me as I added the initial MathJax PR.

Yes 😁

> My first iteration used the MathJax version used in Asciidoctor HTML5. I wanted to have a 1:1 compatibility. As the rendered documents look fine, I think its ok to upgrade, although the test suite is not extensive.

My idea is to upgrade some tools in the ecosystem to make sure that MathJax 3 is compatible so we can safely upgrade Asciidoctor core.
I've opened a pull request to upgrade MathJax in Asciidoctor core and I believe that @mojavelinux is willing to upgrade.

> As you touched the eqnumsValue in this change: I think the logic is now different 

You are right... I don't remember why I did change the logic but I will revert it.
As far as I know `ams` is still supported in MathJax 3 but the value is now in lowercase.
We should probably use `toLowerCase` if the value is not empty.

Thanks for your review!

**Comment by Mogztter** [comment]
@ahus1 I've updated the logic and added a few changes:

- Configure MathJax in an anonymous function javascript to avoid global namespace pollution
- Add tests on eqnums
- Add a `data-type="mathjax-config"` on the `script` element (for testing purpose)
- Declare `MathJax.startup` after the main configuration. Now only `MathJax.startup` is inside the Promise.

**Comment by ahus1** [comment]
I've added a small snippet of latexmath to basic-example.adoc and that rendered as well, therefore I think it's good to go. Still, I don't consider myself as an authority for math in AsciiDoc, just a humble peer reviewer. 

```
latexmath:[C = \alpha + \beta Y^{\gamma} + \epsilon]
```

**Comment by Mogztter** [comment]
> I've added a small snippet of latexmath to basic-example.adoc and that rendered as well, therefore I think it's good to go.

I've added the snippet to `basic-example.adoc`

> Still, I don't consider myself as an authority for math in AsciiDoc, just a humble peer reviewer.

That's all I'm asking :wink: 
Thanks again for your review, you've found a regression that calls for more tests! :1st_place_medal:

**Pull request merged**
